name: Run Tests

# Quand ce workflow doit-il s'exécuter ?
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Les tâches à exécuter
jobs:
  test:
    name: Run Vitest
    runs-on: ubuntu-latest # Système d'exploitation de la machine virtuelle

    steps:
      # Étape 1 : Récupérer le code du dépôt
      - name: Checkout code
        uses: actions/checkout@v4

      # Étape 2 : Installer Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22' # Mise à jour pour correspondre à ta version locale

      # Étape 3 : Installer les dépendances
      - name: Install dependencies
        run: npm install

      # Étape 4 : Exécuter les tests
      - name: Run tests
        run: npm run test